"""
Registro central de features e presets disponiveis no projeto.
"""

from __future__ import annotations

FEATURE_REGISTRY = [
    # Grupo: Retornos
    {
        "name": "Return",
        "label": "Retorno Simples",
        "group": "Retornos",
        "description": "Variação percentual simples de fechamento dia a dia.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Log_Return",
        "label": "Retorno Logarítmico",
        "group": "Retornos",
        "description": "Log-retorno de fechamento diário.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Log_Return_Lag1",
        "label": "Lag 1 de Log-Retorno",
        "group": "Retornos",
        "description": "Log-retorno do pregão anterior.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Log_Return_Lag2",
        "label": "Lag 2 de Log-Retorno",
        "group": "Retornos",
        "description": "Log-retorno de 2 pregões atrás.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Log_Return_Lag3",
        "label": "Lag 3 de Log-Retorno",
        "group": "Retornos",
        "description": "Log-retorno de 3 pregões atrás.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Log_Return_Lag5",
        "label": "Lag 5 de Log-Retorno",
        "group": "Retornos",
        "description": "Log-retorno de 5 pregões atrás.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Rolling_Return_5",
        "label": "Retorno Acumulado (5d)",
        "group": "Retornos",
        "description": "Retorno acumulado nos últimos 5 dias.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Rolling_Return_20",
        "label": "Retorno Acumulado (20d)",
        "group": "Retornos",
        "description": "Retorno acumulado nos últimos 20 dias.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    # Grupo: Tendência
    {
        "name": "SMA_7",
        "label": "Média Móvel Simples 7d",
        "group": "Tendência",
        "description": "Média dos preços de fechamento nos últimos 7 dias.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "SMA_21",
        "label": "Média Móvel Simples 21d",
        "group": "Tendência",
        "description": "Média dos preços de fechamento nos últimos 21 dias.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "Momentum_5",
        "label": "Momentum 5d",
        "group": "Tendência",
        "description": "Razão do fechamento de hoje contra 5 dias atrás.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "RSI_14",
        "label": "Índice de Força Relativa (14d)",
        "group": "Tendência",
        "description": "Mede velocidade e mudança de movimentos de preço.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "MACD",
        "label": "Linha MACD",
        "group": "Tendência",
        "description": "Diferença entre EMAs de 12 e 26 dias.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "MACD_Signal",
        "label": "Sinal do MACD",
        "group": "Tendência",
        "description": "EMA de 9 dias da linha MACD.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "MACD_Hist",
        "label": "Histograma MACD",
        "group": "Tendência",
        "description": "Diferença entre linha MACD e sinal.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    # Grupo: Volatilidade
    {
        "name": "Volatility_21",
        "label": "Volatilidade 21d",
        "group": "Volatilidade",
        "description": "Desvio padrão dos log-retornos nos últimos 21 dias.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "BB_Width",
        "label": "Largura das Bandas de Bollinger",
        "group": "Volatilidade",
        "description": "Mede a dispersão das bandas de volatilidade em relação à média.",
        "requires": ["Close"],
        "available_for_api_closes_only": True,
    },
    {
        "name": "ATR_14",
        "label": "Average True Range (14d)",
        "group": "Volatilidade",
        "description": "Mede a amplitude média real de negociação.",
        "requires": ["High", "Low", "Close"],
        "available_for_api_closes_only": False,
    },
    {
        "name": "Range_Pct",
        "label": "Range Diário %",
        "group": "Volatilidade",
        "description": "Razão da diferença entre Máxima e Mínima em relação ao Fechamento.",
        "requires": ["High", "Low", "Close"],
        "available_for_api_closes_only": False,
    },
    # Grupo: Volume
    {
        "name": "Volume_Z",
        "label": "Volume Normalizado (Z-score)",
        "group": "Volume",
        "description": "Z-score do volume transacionado em janela de 21 dias.",
        "requires": ["Volume"],
        "available_for_api_closes_only": False,
    },
    {
        "name": "Log_Volume",
        "label": "Log do Volume",
        "group": "Volume",
        "description": "Logaritmo natural do volume transacionado.",
        "requires": ["Volume"],
        "available_for_api_closes_only": False,
    },
    # Grupo: Calendário
    {
        "name": "Day_Of_Week",
        "label": "Dia da Semana",
        "group": "Calendário",
        "description": "Representação numérica do dia da semana (0-4 para seg-sex).",
        "requires": ["Date"],
        "available_for_api_closes_only": False,
    },
]

FEATURE_PRESETS = {
    "returns_basic": [
        "Log_Return",
        "Log_Return_Lag1",
        "Log_Return_Lag2",
        "Log_Return_Lag3",
        "Log_Return_Lag5",
    ],
    "returns_trend": [
        "Log_Return",
        "Log_Return_Lag1",
        "Log_Return_Lag2",
        "Log_Return_Lag3",
        "Log_Return_Lag5",
        "Momentum_5",
        "Rolling_Return_5",
        "Rolling_Return_20",
        "SMA_7",
        "SMA_21",
        "MACD",
        "MACD_Signal",
        "MACD_Hist",
    ],
    "returns_volatility": [
        "Log_Return",
        "Log_Return_Lag1",
        "Log_Return_Lag2",
        "Log_Return_Lag3",
        "Log_Return_Lag5",
        "Volatility_21",
        "BB_Width",
        "ATR_14",
        "Range_Pct",
    ],
    "technical_complete": [
        "Log_Return",
        "SMA_7",
        "SMA_21",
        "Volatility_21",
        "Momentum_5",
        "Range_Pct",
        "Volume_Z",
        "RSI_14",
        "MACD",
        "MACD_Signal",
        "MACD_Hist",
        "BB_Width",
        "ATR_14",
        "Log_Return_Lag1",
        "Log_Return_Lag2",
        "Log_Return_Lag3",
        "Log_Return_Lag5",
        "Rolling_Return_5",
        "Rolling_Return_20",
        "Day_Of_Week",
        "Log_Volume",
    ],
}
